-- AlterTable
ALTER TABLE "mother_profiles" ALTER COLUMN "lmpDate" DROP NOT NULL,
ALTER COLUMN "weeksPregnant" DROP NOT NULL,
ALTER COLUMN "weeksPostpartum" DROP NOT NULL,
ALTER COLUMN "babyAgeMonths" DROP NOT NULL,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "babyGender" DROP NOT NULL;
